---

# Install Red Hat development utilities
- name: Install RHEL development tools
  yum:
    name:
      - cmake3
      - devtoolset-7-gcc-c++
      - devtoolset-7-gdb
      - llvm-toolset-7-clang
      - llvm-toolset-7-clang-tools-extra
      - python36
      - python36-pip
      - python36-setuptools
      - rh-git29-git
  state: installed 

# Need to activate SCL Git
#
- name: Activate SCL Git for all sessions 
  lineinfile:
    path: /etc/profile 
    line: source /opt/rh/rh-git29/enable 
