---
# This Playbook runs all the common plays in the deployment

- name: Create development user
  user: name={{ devusername }} password={{ devuserpwd }} comment={{ devusercomment }}

- name: Create code directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ devusername }}" 
    group: "{{ devusername }}"   
    mode: 0775
  with_items:
    - /home/{{ devusername }}/Code/sk3l
    - /home/{{ devusername }}/Code/linux

#- name: Fetch shell utils 
#  git:
#    repo: git@github.com:sk3l/sk3shell.git
#    dest: /home/mskelton/Code/sk3l/sk3lshell
#  git:
#    repo: git@github.com:sk3l/tmux-conf.git
#    dest: /home/mskelton/Code/sk3l/tmux-conf
#  git:
#    repo: git@github.com:sk3l/vim-conf.git
#    dest: /home/mskelton/Code/sk3l/vim-conf

#- name: Create the hosts file for all machines
#  template: src=hosts.j2 dest=/etc/hosts
#
#- name: Create the repository for 10Gen
#  copy: src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo
#
#- name: Create the EPEL Repository.
#  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
#
#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
#
#- name: Create the mongod user
#  user: name=mongod comment="MongoD"
#
#- name: Create the data directory for the namenode metadata
#  file: path={{ mongodb_datadir_prefix }} owner=mongod group=mongod state=directory
#
#- name: Install the mongodb package
#  yum: name={{ item }} state=installed
#  with_items:
#   - libselinux-python
#   - mongo-10gen
#   - mongo-10gen-server
#   - bc
#   - python-pip
#
#- name: Install the latest pymongo package
#  pip: name=pymongo state=latest use_mirrors=no
#
#- name: Create the iptables file
#  template: src=iptables.j2 dest=/etc/sysconfig/iptables
#  notify: restart iptables
